spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  jpa:
    hibernate:
      ddl-auto: update  # (개발 중엔 update, 운영은 validate 또는 none)
    show-sql: true
#    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${APP_BASE_URL}/login/oauth2/code/kakao
            scope:
              - profile_nickname
#              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # ??
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

riot:
  api:
    key: ${RIOT_API_KEY}

# 파일 업로드 경로 설정
custom:
  upload-path:
    qna: ${UPLOAD_BASE_DIR:${user.dir}}/upload/qna
    clan: ${UPLOAD_BASE_DIR:${user.dir}}/upload/clan